.github/workflows/ci.yml
clarifai_grpc/channel/clarifai_channel.py
clarifai_grpc/channel/errors.py
clarifai_grpc/channel/grpc_json_channel.py
clarifai_grpc/channel/http_client.py
tests/test_integration.py

This PR changes the GET parameter encoding, so it works on dictionary parameters, such as getting model version metrics with custom fields.
It also adds a large integration test that tests the above request + several others, to get a better confidence everything is integrated correctly.

Encode GET parameters + add a test

---

clarifai_grpc/channel/http_client.py
tests/helpers.py
tests/test_integration.py

This PR makes the failed or mixed response in a JSON channel to be handled in the same way as in the gRPC channel.
It also improves tests' structure.
Closes #4 .

Graceful failed response handling

---

tests/common.py
tests/test_deep_training.py
tests/test_image_predict.py
tests/test_public_models_predicts.py
tests/test_video_predict.py

On non-prod, it's possible that PostModelOutputs will return a temporary 504 response.
We don't care about those as long as, after a few seconds, the response is a success.

Retry PostModelOutputs on non-prod when the response is 504

---

.github/workflows/run_tests.yml
tests/common.py
tests/test_deep_training.py
tests/test_predict_on_all_public_models.py
tests/test_predict_on_some_public_models.py

This adds a test that goes through all public models and makes a `PostModelOutputs` (prediction) method call, to ensure the response is a success.

Add testing PostModelOutputs on all public models

---

clarifai_grpc/channel/grpc_json_channel.py
tests/test_collaborators.py

1. Run `test_list_collaborators_with_pat` test
* Test passes
* Test fails
```
17:57:45     @both_channels
17:57:45     def test_list_collaborators_with_pat(channel):
17:57:45         stub = service_pb2_grpc.V2Stub(channel)
17:57:45         metadata = (("authorization", "Key %s" % os.environ.get("CLARIFAI_PAT_KEY")),)
17:57:45     
17:57:45         list_apps_response = stub.ListApps(service_pb2.ListAppsRequest(), metadata=metadata)
17:57:45         # We should have at least one app. If this turns out not to be the case and the
17:57:45         # test fails, we should create it in this test.
17:57:45 >       assert list_apps_response.apps
17:57:45 E       assert []
17:57:45 E        +  where [] = status {\n  code: CONN_KEY_INVALID\n  description: "Invalid API key or Invalid API …
```

[TP-872] :bug: Fix missing user id

---

README.md

Added additional output for context in the event there is an error.  Currently it will generally just print out 'Failure' to the user, versus the specific reason (too large of an image, etc.).

Added more information to output in case there is an error

---

README.md
clarifai_grpc/channel/clarifai_channel.py

- Added CLARIFAI_GRPC_PORT as an environmental variable so the port for connecting via insecure grpc channels can be customized for enterprise customers
- Updated the documentation to give examples of setting the CLARIFAI_GRPC_BASE, CLARIFAI_GRPC_PORT, and CLARIFAI_API_BASE for enterprise customers
- Updated the example in the documentation to use PATs instead of APP Keys.

Fix insecure grpc channel port

---

clarifai_grpc/channel/grpc_json_channel.py

- Currently we are only registering the additional bindings or the original binding, but not both. I discovered this with this line: https://github.com/Clarifai/clarifai-python-grpc/blob/6e68e0b1d09e0ae5c76e28f7fa838f28ec39c20e/long_tests/test_deep_training.py#L114
We weren't registering the original DeleteModels bindings, so when using a PAT in the request, it was failing, because we weren't sending the app_id or user_id since the additional binding doesn't require it.

[EAGLE-1645] Register all bindings

---

tests/test_public_models_predicts.py

Video model tests don’t test the models in a different way than the existing image tests. The video tests only test the media processing assuming image tests are passing. This PR will change video tests to only run on the general model.

reduce video tests to only run on general model

---

setup.py

This should fix the problem with a fresh install 
```
ERROR: googleapis-common-protos 1.56.2 has requirement protobuf<4.0.0dev,>=3.15.0, but you'll have protobuf 4.21.1 which is incompatible.
```

Set upper protubuf version

---

scripts/app_and_key_for_tests.py

* `app_and_key_for_tests.py` requests fail silently
```
CLARIFAI_API_BASE:https://api.clarifai.com
Creating a new app and keys, so the test run is completely isolated from test runs.
Traceback (most recent call last):
File "scripts/app_and_key_for_tests.py", line 201, in <module>
run(arguments=sys.argv[1:])
File "scripts/app_and_key_for_tests.py", line 183, in run
raise Exception('--create-workflow takes one argument')
Exception: --create-workflow takes one argument
```

[TP-1132] :recycle: Add assertions to app_and_key_for_tests.py

---

scripts/app_and_key_for_tests.py

When running `export APP_ID=$(python $CLARIFAI_PYTHON_GRPC_ROOT/scripts/app_and_key_for_tests.py --create-app python-github)` , no output is displayed in case of error.
* Replace usage of `print` and `os._exit` with `raise`.

[TP-1138] :recycle: Fix raising error in app_and_key_for_tests.py

---

tests/client/test_secure_data_hosting.py

deletes are async and posting sometime errors out because we test with two channels (JSON/GRPC) back-to-back

[EAGLE-2594] fix race condition

---

tests/client/test_secure_data_hosting.py

* API does now return `404` instead of `400` when no auth is provided for SDH input urls

[LT-4282] Fix SDH expected status

---

tests/client/test_secure_data_hosting.py

* No need to support old status `400` in tests

[LT-4282] Update SDH expected status

---

tests/client/test_input_search_legacy.py

* Strict validation for search unsupported fields was enabled.
* Test `tests/client/test_input_search_legacy.py::test_search_by_image_bytes` started to fail with error `40002 Invalid search request Search output has unsupported field set: 'data.image.base64[]'. Did you mean to set 'input.data.image.base64[]'? Check your request fields.`
* Searching using `data.image.base64[]` field did actually not perform any ranking. The field was ignored.
* In order to perform ranking by image bytes, we need to use `input.data.image.base64[]` field.
* Use `input.data.image.base64[]` instead of `data.image.base64[]`

[TP-1314] :bug: Fix using unsupported search field

---

tests/client/test_image_predict.py

API endpoint `PostModelOutputs` was changed to return more specific error code in case of failure.

[TP-1333] Update test expected status

---

scripts/app_and_key_for_tests.py

We want these scripts to be more flexible to use in non https situations

Allow non https schemes in grpc test scripts

---

clarifai_grpc/channel/clarifai_channel.py

- Add custom root certificates support for secure gRPC connection
Manual local tests with openssl generated server cred, key
Server
```python
import grpc
from concurrent import futures
from clarifai_grpc.grpc.api import service_pb2_grpc
from clarifai_grpc.grpc.api import service_pb2
from clarifai_grpc.grpc.api.status import status_pb2
import time
class ImagePredictionService(service_pb2_grpc.V2Servicer):
def PostModelOutputs(self, request, context):
print("Received a PostModelOutputsRequest")
return service_pb2.MultiOutputResponse(
status=status_pb2.Status(code=10000, description="Success")
)
with open('/Users/sainivedh/Desktop/server.crt', 'rb') as f:
server_certificate = f.read()
with open('/Users/sainivedh/Desktop/server.key', 'rb') as f:
server_private_key = f.read() …
```

[DEVX-400] Add custom root certificates support

---

clarifai_grpc/channel/errors.py
clarifai_grpc/channel/grpc_json_channel.py

```
FAILED tests/client/test_collaborators.py::test_list_collaborators_with_pat - AttributeError: 'GRPCJSONChannel' object has no attribute 'unary_stream'
```
* To quickly fix this, add the missing methods and mark them as not implemented. This will allow the channel to be initialised without breaking.

[TP-1454] Fix channel missing attributes

---

scripts/app_and_key_for_tests.py
tests/common.py

We want to be able to run these tests without a secure grpc channel

Allow insecure grpc during tests

---

tests/client/test_dataset_version_export.py

* Recent API change: dataset version export URLs are now served through SDH
* Add authorization for SDH urls

[LT-5283]  Fix downloading dataset version export URLs

---

tests/client/test_dataset_version_export.py
tests/common.py

* Previous commit 22b717e70c651c87a9a8641149489157d3c11f5f did not set the headers as expected, which caused ` AttributeError: 'tuple' object has no attribute 'items'` error
* Set headers in a map instead of a list

[LT-5283] Fix setting authorization for SDH urls

---

scripts/app_and_key_for_tests.py

After https://github.com/Clarifai/clarifai/pull/17643 was merged, `Universal` workflow is the default when nothing is specified.
Client tests rely on the workflow being `General`. So set the workflow as `General` while creating the app

use general workflow while creating app

---

tests/common.py

Temporary fix to handle seemingly transient AWS errors until LT-5281 is implemented (should be picked up by DaLi in the next sprint starting in 1 week).
Expect to alleviate the deep train client test alerts, but will not resolve the timeout errors.
Since `deep-training-client-tests` [checks out this repo](https://github.com/Clarifai/crons-api-client-tests/blob/f05b7ca6349b26c3a726389969cdf84c46a76dc9/.github/workflows/deep-training-client-tests.yml#L34), we do not need to bump versions. We should also merge this PR before https://github.com/Clarifai/crons-api-client-tests/pull/74.

[EAGLE-4649] add retry to wait_for_model_trained

---

tests/common.py

* Make it clearer when a test is executed over multiple channels
* Add new methods `run_tests_using_channels` & `run_tests_using_channels_async` that use `@pytest.mark.parametrize` to create subtests for each test channel

[TP-1786] Create subtests for each channel in client tests

---

tests/public_models/test_public_models_predicts.py

* Highlight models being tested
* Continuation of 35aa6d4
* Use `@pytest.mark.parametrize` to create sub-tests for each test model

[TP-1787] Create sub-tests for each model in client clients - part 2

---

clarifai_grpc/channel/http_client.py

* Track requests made by python clients that use json channel
* this does not apply to grpc clients
* currently, the way to use customize headers for grpc clients is to use `metadata` parameter, as added in b292466

[TP-1532] Set req ID prefix header for json channel

---

tests/client/test_model_crud.py
tests/public_models/test_public_models_predicts.py

The test test_model_creation_training_and_evaluation is causing failures in Cron runs:
```INTERNALERROR> AssertionError: ('tests/client/test_model_crud.py::test_model_creation_training_and_evaluation[json]', <WorkerController gw1>)```
As a temporary measure, we're skipping the tests within the function body rather than using a decorator.
This is a blind fix, as we suspect the issue may be related to the use of the @skip decorator.

Skip tests inside the function instead of Decorators
